Add Set and Add -FGTSystemZone functions in zone.ps1
FortiPower/PowerFGT pull request #109
Opened 2020-08-06 15:33 UTC by CedricMoreau

2020-08-06 17:17 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/interface.ps1
> +
Wrong PR

2020-08-06 17:17 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        $zone | add-member -name "q_origin_key" -membertype NoteProperty -Value $name
No needed

2020-08-06 17:18 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Invoke-FGTRestMethod -uri 'api/v2/cmdb/system/zone' -method 'POST' -body $zone -connection $connection | Out-Null
Not possible to add member zone too ?

2020-08-06 17:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Get-FGTSystemZone -name $name
Add -connection parameter (for multi connection

2020-08-06 17:20 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        $get_interface = Get-FGTSystemInterface -name $interface
?

2020-08-06 17:21 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Get-FGTSystemZone -name $name
-connection

2020-08-06 17:24 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +                $member_attributes.add( 'q_origin_key', $member)
No needed

2020-08-08 07:09 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +            Throw "You need to specifiy a name"
Use mandatory parameter

2020-08-08 07:10 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +                $get_interface = Get-FGTSystemInterface -name $member
Missing connection parameter and don’t check for the moment, I will plan a cache for avoid to check for each interface (can be very slow...)

2020-08-08 07:11 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        [string]$name,
Use pipeline (And use another variable like zone)

2020-08-08 07:12 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        [string]$name,
Add validate zone

2020-08-08 07:13 UTC, alagoutte commented on Tests/integration/Zone.Tests.ps1
> +        Add-FGTSystemZone -name "PowerFGT" -intrazone deny -interfaces port9,port10
Use variable for name of zone

2020-08-08 07:13 UTC, alagoutte commented on Tests/integration/Zone.Tests.ps1
> +    It "Try to add zone without name" {
Not needed

2020-08-08 07:14 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        $null = Invoke-FGTRestMethod -method "DELETE" -uri "api/v2/cmdb/system/zone/${name}" -connection $connection
Add should procees

2020-08-08 07:15 UTC, alagoutte commented on Tests/integration/Zone.Tests.ps1
> +    It "Add zone PowerFGT" {
Try with intrazone deny or allow

Try with 0 interface, 1, 2 ...

2020-10-04 08:19 UTC, alagoutte requested changes
Look good but need some change before merge

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Private/Confirm.ps1
> +        throw "Element specified does not contain an name property."
an -> a name

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Private/Confirm.ps1
> +        throw "Element specified does not contain a intrazone property."
a -> an intrazone

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Invoke-FGTRestMethod -uri 'api/v2/cmdb/system/zone' -method 'POST' -body $zone -connection $connection | Out-Null
Add variable for uri ?

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Set a zone
Configure a zone (name, intrazone, member...)

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Set-FGTSystemZone -name PowerFGT -intrazone deny -interfaces port5,port6
add more example (only change name, intrazone, member...)

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Set-FGTSystemZone -name PowerFGT -intrazone deny -interfaces port5,port6
also use pipeline for example

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        [string]$zone_name,
name ?

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Remove-FGTSystemZone -zone PowerFGT
add example with confirm parameter

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'medium')]
high impact !

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Remove-FGTSystemZoneMember -name PowerFGT -interface port9
a example with multiple port ?

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Remove-FGTSystemZoneMember -name PowerFGT -interface port9
use also pipeline for example

2020-10-04 08:19 UTC, alagoutte commented on PowerFGT/Public/cmdb/system/zone.ps1
> +        Add-FGTSystemZoneMember -name PowerFGT -interface port9
pipeline for eample...

2020-10-04 08:19 UTC, alagoutte commented on Tests/common.ps1
> +$script:pester_zone1 = "PowerFGT1"
pester_zone1 ? (same after)

2020-10-04 08:19 UTC, alagoutte commented on Tests/integration/Zone.Tests.ps1
> +        Get-FGTSystemZone -name $pester_zone1 | Set-FGTSystemZone -interfaces $pester_port1,$pester_port2
it is the same interface (use $pester_port3 and 4?)

2020-10-04 08:19 UTC, alagoutte commented on Tests/integration/Zone.Tests.ps1
> +        Get-FGTSystemZone $pester_zone1 | Remove-FGTSystemZone
it is the same test ?

2020-10-06 20:40 UTC, alagoutte commented on Tests/integration/Zone.Tests.ps1
> +#
add your credit (and also on Zone.ps1 ;))

2020-11-19 12:11 UTC, jelmerj commented
This pull request needs support for the vdom parameter. Please note that the vdom parameter also needs to be added to the Get-FGT* calls which are called from within the functions

2020-11-19 17:09 UTC, alagoutte commented
> 
> 
> This pull request needs support for the vdom parameter. Please note that the vdom parameter also needs to be added to the Get-FGT* calls which are called from within the functions
> I could help to add it, but I'm not an expert on Git and don't know how I could contribute to a pull request from someone else.

Hi, Good catch thanks !
it is missing for this cmdlet ! (i need to look for add test with vdom...)

What other get cmdlet do you have where missing vdom parameter ?

i can help you about git, you can contact me by mail (look file header) or other (twitter...)

2020-11-21 10:33 UTC, merged