Add Local User (Add/Set/Remove)
FortiPower/PowerFGT pull request #190
Opened 2022-05-31 09:35 UTC by CedricMoreau

2022-05-31 10:02 UTC, alagoutte requested changes

2022-05-31 10:02 UTC, alagoutte commented on Tests/integration/UserLocal.Tests.ps1
> +        It "Change MFA" {
enable MFA ?

2022-05-31 10:02 UTC, alagoutte commented on Tests/integration/UserLocal.Tests.ps1
> +        AfterAll {
use AfterEach ?

2022-06-14 09:29 UTC, CedricMoreau commented on PowerFGT/Public/cmdb/user/local.ps1
> +        [string]$two_factor,
Why

2022-06-14 10:30 UTC, alagoutte commented on PowerFGT/Public/cmdb/user/local.ps1
> +        [string]$two_factor,
avoid duplicate entry...

2024-08-26 13:14 UTC, alagoutte commented
/azp run

2024-08-26 15:02 UTC, alagoutte commented
/azp run

2024-08-27 07:46 UTC, alagoutte commented
/azp run

2024-08-27 13:48 UTC, alagoutte commented
/azp run

2024-08-28 14:13 UTC, alagoutte commented
/azp run

2024-08-29 08:03 UTC, alagoutte commented on PowerFGT/Public/cmdb/user/local.ps1
> +        [SecureString]$passwd,
$password ?

2024-08-29 08:04 UTC, alagoutte commented on Tests/integration/UserLocal.Tests.ps1
> +    It "Get ALL User Local with -skip" {
add also with with -meta parameter

2024-08-29 08:04 UTC, alagoutte commented on Tests/integration/UserLocal.Tests.ps1
> +    Context "Local User (Email, MFA, etc" {
missing )

2024-08-29 08:04 UTC, alagoutte commented on Tests/integration/UserLocal.Tests.ps1
> +
missing some case like radius, tacacs (and ldap) server ?

2024-08-29 08:05 UTC, alagoutte commented on Tests/integration/UserLocal.Tests.ps1
> +        It "Remove User Local $pester_userlocal by pipeline" {
remove also by id ?

2024-08-30 09:51 UTC, alagoutte commented on PowerFGT/Public/cmdb/user/local.ps1
> +        [Parameter(Mandatory = $false)]
add also -data parameter like other add function ;)

2024-08-30 14:33 UTC, alagoutte commented
/azp run

2024-08-30 15:40 UTC, alagoutte commented
/azp run

2024-09-02 13:04 UTC, alagoutte commented
/azp run

2024-09-03 09:16 UTC, alagoutte commented
/azp run

2024-09-04 08:45 UTC, alagoutte commented
/azp run

2024-09-04 10:12 UTC, alagoutte commented
/azp run

2024-09-04 13:23 UTC, alagoutte commented
/azp run

2024-09-04 15:28 UTC, merged