Update backup.ps1
FortiPower/PowerFGT pull request #272
Opened 2024-10-14 19:54 UTC by johan-kummeneje-complior

Fixing issue 271

2024-10-15 14:43 UTC, alagoutte commented
Hi Johan,

May be a better to add -scope parameter ? because if you are using vdom but you want to have a global config...

2024-10-15 14:52 UTC, johan-kummeneje-complior commented
Hi Alexis, 
it really doesn't make sense to want the global config and passing a vdom as argument.
Doing so just gives you the full config anyways. If one wants a vdom, just pass the vdom as argument. 

Best Regards
Johan

2024-10-15 15:13 UTC, alagoutte commented
you can use connect-fgt with directly vdom parameter and it is "store" but maybe you want to get global config....

2024-10-26 16:35 UTC, johan-kummeneje-complior commented
Ok, that should be possible to do. I will try to squeeze it in in the next few weeks.

2024-10-26 18:12 UTC, johan-kummeneje-complior commented
@alagoutte 

I fixed the code so it works both automatically and also if needed you can put the scope parameter in.

Best Regards
Johan

2024-10-27 13:04 UTC, alagoutte commented
Hi Johan,

Thanks, i will try to look this week

2024-10-31 15:22 UTC, alagoutte commented on PowerFGT/Public/monitor/system/config/backup.ps1
> -        #before 7.6.x, config/backup is available with get method and using paramater
why change comment ?

2024-10-31 15:22 UTC, alagoutte commented on PowerFGT/Public/monitor/system/config/backup.ps1
> +#
?

2024-11-01 13:05 UTC, johan-kummeneje-complior commented on PowerFGT/Public/monitor/system/config/backup.ps1
> -        #before 7.6.x, config/backup is available with get method and using paramater
Not intentionally changed.

2024-11-01 13:05 UTC, johan-kummeneje-complior commented on PowerFGT/Public/monitor/system/config/backup.ps1
> +#
Very strange. they seem to be the same.

2024-12-07 14:18 UTC, alagoutte requested changes

2025-01-03 20:12 UTC, merged